# Generated by Django 5.0.3 on 2024-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField()),
                ('localizacao', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
    ]
