# Generated by Django 4.1.13 on 2024-03-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaDeAula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saladeaula',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='saladeaula',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='saladeaula',
            name='localizacao',
        ),
        migrations.AlterField(
            model_name='saladeaula',
            name='capacidade',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaDeAula.saladeaula')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaDeAula.saladeaula')),
            ],
        ),
    ]
